### PR TITLE
Webpack 5 support

### PR DESCRIPTION
**Pull request by tcoats**
Support webpack 5 peer dependency.
From what I can tell this is everything needed for Webpack 5 support.

### CODE REVIEW

**Comment by Va1** [comment]
hi @tcoats . thank you very much for your contribution.

did you test yourself that the plugin is compatible with Webpack 5?

**Comment by Locheed** [comment]
@tcoats @Va1 Could we rush this release a bit? The plugin works nicely with Webpack 5. Just have to install it with "npm install --legacy-peer-deps" or with yarn.

**Comment by danielegiorgis** [comment]
:) 🙏🏻? please? :)
ps. Thank for all your effort!

**Comment by Va1** [comment]
sorry for delay. released as [v2.3.0](https://github.com/Va1/browser-sync-webpack-plugin/releases/tag/v2.3.0)

**Comment by danielegiorgis** [comment]
No problem, indeed! thank you so much and forgive me for pinging! ❤️

**Comment by Va1** [comment]
@danielegiorgis no worries, mate. have a nice one :)

**Pull request merged**
